src/modal.rs
Before this PR, if you create a modal that has children but not a description, there'll be an empty div with an extra 16 px of padding above the children. This PR only creates the div for the description text if that text is not empty.
=> Avoid creating extra body div in Modal if description is empty.

src/components/modal.rs
Sometimes you don't want to allow user to close modal window (for example if you wait for operation to finish).
=> Modal: disable close button

generator/icons/icons.mjs, src/components/pagination.rs, src/icon/generated.rs
Inspired by the ReactJS equivalent of Patternfly https://www.patternfly.org/v4/components/pagination#bottom
- The `Pagination` component will accept an optional property `is_bottom: bool`, if `is_bottom=true` then the dropdown for selecting the number of items per page will appear on top of the component and using the appropriate arrow icons.
A common use case is to have pagination on top and at the bottom of a table. Both pagination components must shown the same data. While creating this PR I found out that if there are more than 1 PAGINATION component then a change of the pages on one of them is not reflected in the other PAGINATION components (see video for better understanding).
[Screencast from 2023-06-19 09-54-24.webm](https://github.com/ctron/patternfly-yew/assets/2582866/e4dd7b5d- …
=> feat(pagination): add is_bottom

src/components/pagination.rs
- `pf-m-bottom` is a class that should be set at the main `div` component when the selected position is BOTTOM
- The style `--pf-v5-c-pagination__nav-page-select--c-form-control--width-chars` should be set in the component itself rather than expecting users to set this value. Moreover, this style should change depending of the max page
```
--pf-v5-c-pagination__nav-page-select--c-form-control--width-chars: MAX_PAGE
```
=> fix(pagination): pf-m-bottom class is not set & width of page number input should be set in the component

Cargo.toml, src/components/table/column.rs, src/components/table/header.rs, src/components/table/mod.rs
Inspired by https://github.com/patternfly-yew/patternfly-yew/compare/main...carlosthe19916:sorting-controlled?expand=1
- If use does not set the status of the current sorting then the context header takes care of saving the status
- If user do set the status of the current sorting then this status is used
This is useful on scenarios where the table needs to be re-rendered, in this scenario the internal Context is lost therefore is advised the user to manage the status
=> Sorting table: Allow controlled and uncontrolled sorting status

src/components/table/mod.rs
If the table wants to render expandable columns, then the current table adds an empty column to the header. That behavior was added for the use case of "extended content table" where the arrow in the first column is added. However, when expanded content is applied to cells, then there is no need for empty columns in the header
=> fix: Expandable cells table show empty header column

src/components/dropdown.rs
I made a mistake on the last PR because the popper for the items isn't resized along with the dropdown.
This is still a draft because it isn't responsive. You need to close and reopen the dropdown for the correct size to display for the items.
I have some commented lines where I attempted to make it responsive. However, as soon as I have a `UseStateHandle` for the style being passed to the `Menu`, the item are rendered above the dropdown and have the full width of the window.
Will look into it more tomorrow.
=> hotfix menu items not full width

src/components/tabs/router.rs
At first glance I don't see any drawbacks to this. Would be cool to see the `TabRouterItem` component become more similar to the `Tab` component in general but I think this is a good start.
=> Use TabTitle instead of String for router tabs

src/components/dropdown.rs
In a minimal example non-full-width dropdowns worked fine but in a more involved setting they also need the width modifier.
This is also in line with [patternfly-react's popper implementation](https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/helpers/Popper/Popper.tsx#L387).
We should get this merged to avoid breakage but I actually think we should maybe move the modifier into popper-rs instead to achieve more similarity to patternfly-react's popper.
=> Use width mods for all dropdowns

Cargo.toml, src/components/button/mod.rs, src/components/dual_list_selector/control/button.rs, src/components/dual_list_selector/control/mod.rs, src/components/dual_list_selector/control/wrapper.rs, src/components/dual_list_selector/item_renderer.rs, src/components/dual_list_selector/list/item.rs, src/components/dual_list_selector/list/list_inner.rs, src/components/dual_list_selector/list/mod.rs, src/components/dual_list_selector/list/wrapper.rs, src/components/dual_list_selector/mod.rs, src/components/dual_list_selector/pane.rs, src/components/mod.rs, src/prelude.rs
Implements the [dual list selector](https://www.patternfly.org/components/dual-list-selector/).
Currently supported properties:
- disabled
- pane titles
- options
- pane statuses
- onlistchange event
Currently unsupported properties but planned before merge:
Currently unsupported properties which aren't planned for the merge:
- id
- tree
- onoptioncheck event
- aria
- searchable
- filtering
- dragging
- actions
- keyboard navigation
Similar to how the table is currently implemented, I've defined a new trait `DualListSelectorItemRenderer` which has a blanket implementation for types implementing `Debug + Clone + PartialEq + ToHtml + 'static`. 
This type is used to render a single entry of a list in each of the two panes (available and chosen) by calling `to_html`.
~~1. I see anymap is …
=> Implement dual list selector

src/components/page/section.rs
I noticed the padding wasn't correct on the breadcrumb page sections. I checked the patternfly-react implementation and they include the inner div whenever the page section is width limited regardless of page section type: https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Page/PageSection.tsx#L134
This also corrects the behavior the breadcrumbs.
=> relax rules for creating an inner page__main-body div

Cargo.toml, src/components/button/mod.rs, src/components/mod.rs, src/components/search_input/mod.rs, src/components/text_input_group.rs, src/prelude.rs
Implements the [search input](https://www.patternfly.org/components/search-input/) component without the advanced configuration.
Demos can be found (and later merged) here: https://github.com/adogcalledspot/patternfly-yew-quickstart/tree/search_input
=> Implement SearchInput

src/components/table/column.rs
The Patternfly-ReactJS implementation uses a specific library for tooltips react-popper, to read more here is the link https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/helpers/Popper/thirdparty/README.md. 
I could not find an equivalent library that we can use in Yew; therefore, I suggest using just the HTML supported attributes for adding tooltips to the table headers:
Disadvantages:
-  The style (visualization) is slightly different to the Patternfly ReactJS implementation since we are relying on purely the HTML tooltip
- In Patternfly ReactJS the tooltips only appear when the header exceeds the width of the column; however, with the HTML tooltips the tooltips appear all the time when the user puts his mouse over.
[Screencast from 2023-12-04 …
=> feat: add table html header tooltip

Cargo.toml, src/components/mod.rs, src/components/number_input.rs, src/prelude.rs
Adds support for the number input component.
Has support for all props except:
- input aria label since our text inputs don't have an aria label prop
- onblur because I do not understand when this is supposed to blur and why it would
- extra text input props because I was too lazy
- keyboard buttons (seems like something that can be integrated well once the keyboard handling moves forward)
Quickstart PR coming up right away
=> feat(NumberInput): Implement NumberInput

src/components/mod.rs, src/components/simple_list.rs, src/prelude.rs
This adds the SimpleList component.
There is some discussion to be had about the interfaces.
The SimpleList is either grouped or not, never both.
If it is grouped, it needs `SimpleListGroup`s at the top level.
If it isn't grouped then it needs `SimpleListItem`s at the top level.
There are also differences in the content, so I split the two up into separate components to try and enforce some rules.
Due to state management having to occur outside of the component, the user will probably want to abstract the `SimpleListItem`:
```rust
#[function_component(Application)]
fn create_bucket() -> Html {
let selected = use_state(|| 0);
let onclick =  use_callback(selected.clone(), |id, selected| {
log::info!("Setting to {id}");
selected.set(id)
});
html!  {
<SimpleList>
<Item id=0 …
```
=> feat(SimpleList): Add SimpleList component

src/components/card/mod.rs, src/components/menu/item.rs, src/components/progress.rs, src/components/toolbar/group.rs, src/components/toolbar/item.rs
It's called "class" pretty much everywhere else so using "additional_class" seems inconsistent.
=> refactor: rename additional_class to class

src/components/table/mod.rs, src/components/table/model/memoized.rs, src/components/table/model/mod.rs, src/components/table/model/state.rs
Adds two callbacks which both pass in the `Item` which is shown by the row in the table:
- One for adding an onclick handler
- One for deciding whether the row is selected.
For some reason the compiler can't handle the type signature of `Callback<M::Item>` and keeps complaining that it can't compare `<M as TableModel<C>>::Item` with `<M a TableModel<C>>::Item` even though it doesn't have to.
Saying `Callback<M as TableModel<C>>::Item>` fixes this.
Since the callback argument needs to be cloned into the callback, this adds a `Clone` trait bound on table data which I don't see as much of an issue.
=> feat(Table): Clickable rows

src/components/alert.rs, src/components/breadcrumb/mod.rs, src/components/button/mod.rs, src/components/card/mod.rs, src/components/chip.rs, src/components/clipboard.rs, src/components/form/checkbox.rs, src/components/form/input.rs, src/components/form/radio.rs, src/components/form/select.rs, src/components/menu/mod.rs, src/components/modal.rs, src/components/nav/mod.rs, src/components/switch.rs, src/components/table/mod.rs, src/components/tabs/router.rs, src/components/tabs/simple.rs, src/components/title.rs, src/components/toolbar/mod.rs
Closes #129.
Dropped OUIA support for the clipboard since memoization is awkward in struct components.
=> feat(ouia): store ID in components

Cargo.toml, src/core/breakpoint.rs
Adds helper  functions for getting the current breakpoint and for listening to changes in breakpoints.
Example uses:
```rust
let breakpoint =  use_breakpoint();
let button = use_memo(breakpoint.clone(), |breakpoint| match breakpoint {
Breakpoint::None => html!(<Button icon={Icon::Upload} {onclick} />,
_ => html!(<Button icon={Icon::Upload} {onclick} label="Select from disk" variant={ButtonVariant::Secondary} />
});
```
```rust
<Page {sidebar} open={Breakpoint::current() > Breakpoint::Medium} />
```
=> feat(Breakpoint): Add hook for getting updates on breakpoint changes

Cargo.toml, src/components/breadcrumb/mod.rs
BREAKING CHANGE: Build will fail for users who explicitly enabled the "router" feature
Having single dependency feature aliased with a different alias is unnecessary. If there is a need to add more dependencies, it's easy to re-add alias with the same name :)
=> refactor: Remove unnecessary single-dependency feature

src/components/form/area.rs, src/components/form/input.rs, src/components/text_input_group.rs
Previously, the use_effect_with call was invoked with the NodeRef on the respective components' Properties, which works well if user code passes a stable NodeRef in as a prop; if the prop gets defaulted though, that value changes every time through the re-render... which would auto-focus the field everytime an unrelated field in the form changed.
So instead, pass the value of the autofocus prop as an effect condition, and move the input ref the traditional way (via cloning/move closure capture). This ensures that the effect is triggered only once on first render, and then only when the autofocus prop changes.
Refs: #145
Fixes: #145
=> fix: Dispatch the autofocus effect on value of autofocus prop

src/components/page/mod.rs
The Page component is slightly modified in a such way that if one decides to make a page without a sidebar (aka Horizontal navigation) then the bars button will not be displayed.
=> Toggle button (bars)  not shown if sidebar is empty

src/layouts/gallery.rs, src/utils/mod.rs, src/utils/wrap.rs
Unless every direct child of the gallery has a key element, every time the set of children changes, *every* child will be re-rendered, which leads to scroll state confusion and bad performance of the gallery.
So, let's promote up the child's `key` if one is set. As the `html!` macro lacks a way to only set a property conditionally (as for optional props like `key`), this requires rewriting the wrapping logic to use the virtual DOM directly.
Fixes #148
=> Promote gallery element keys into their wrapper divs

src/components/accordion/mod.rs, src/components/alert.rs, src/components/chip_group.rs, src/components/modal.rs, src/layouts/bullseye.rs, src/utils/wrap.rs
Same as #149, this change pulls all the list-like components' child component key properties up into the elements introduced that wrap the children. This should reduce the need to re-compute child components with larger children or many children (like accordions).
=> Promote keys from all list-like components' child components

src/components/modal.rs
The class pf-v5-l-gallery__item applied to the body of the modal since v 0.6.1 has been replaced with pf-v5-c-modal-box__body because otherwise the elements have wrong padding.
=> Restored padding within modal body
